
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 21.2.0
      uses: actions/setup-node@v4
      with:
        node-version: '21.2.0'

    - name: Install dependencies
      run: npm install

    - name: Build and publish app
      env: 
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_OWNER: ${{ secrets.GH_OWNER }}
        GITHUB_REPO: ${{ secrets.GH_REPO }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run build
